changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: "🚀 Features"
      labels:
        - enhancement
    - title: "🐛 Fixes"
      labels:
        - bug
    - title: "📚 Documentation"
      labels:
        - documentation
    - title: "📦 Dependencies"
      labels:
        - dependencies
        - github_actions
    - title: "🧰 Other changes"
      labels:
        - "*"
